--------------------------------------------------------
-- Archivo creado  - miércoles-diciembre-07-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AFICION
--------------------------------------------------------

  CREATE TABLE "HR"."AFICION" 
   (	"AFICION_ID" NUMBER(*,0), 
	"NOMBRE_DE_GUERRA" VARCHAR2(50 BYTE), 
	"EQUIPO_ID" NUMBER(*,0), 
	"SEGUIDOR_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CANTICO
--------------------------------------------------------

  CREATE TABLE "HR"."CANTICO" 
   (	"CANTICO_ID" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(200 BYTE), 
	"AFICION_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EQUIPO
--------------------------------------------------------

  CREATE TABLE "HR"."EQUIPO" 
   (	"EQUIPO_ID" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"ESTADIO_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ESTADIO
--------------------------------------------------------

  CREATE TABLE "HR"."ESTADIO" 
   (	"ESTADIO_ID" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"FECHA_CREACION" DATE, 
	"NUMERO_ASIENTOS" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JUGADOR
--------------------------------------------------------

  CREATE TABLE "HR"."JUGADOR" 
   (	"JUGADOR_ID" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"EQUIPO_ID" NUMBER(*,0), 
	"POSICION" VARCHAR2(50 BYTE), 
	"NUMERO_CAMISETA" NUMBER(*,0), 
	"SALARIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SEGUIDOR_PELIGROSO
--------------------------------------------------------

  CREATE TABLE "HR"."SEGUIDOR_PELIGROSO" 
   (	"SEGUIDOR_ID" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"AFICION_ID" NUMBER(*,0), 
	"FECHA_NAC" DATE, 
	"DNI" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.AFICION
SET DEFINE OFF;
REM INSERTING into HR.CANTICO
SET DEFINE OFF;
REM INSERTING into HR.EQUIPO
SET DEFINE OFF;
Insert into HR.EQUIPO (EQUIPO_ID,NOMBRE,ESTADIO_ID) values ('1','REAL MADRID','1');
REM INSERTING into HR.ESTADIO
SET DEFINE OFF;
Insert into HR.ESTADIO (ESTADIO_ID,NOMBRE,FECHA_CREACION,NUMERO_ASIENTOS) values ('1','BERNABEU',to_date('01/02/90','DD/MM/RR'),'80000');
REM INSERTING into HR.JUGADOR
SET DEFINE OFF;
Insert into HR.JUGADOR (JUGADOR_ID,NOMBRE,EQUIPO_ID,POSICION,NUMERO_CAMISETA,SALARIO) values ('1','CRISTIANO ','1','DELANTERO','7','30000');
Insert into HR.JUGADOR (JUGADOR_ID,NOMBRE,EQUIPO_ID,POSICION,NUMERO_CAMISETA,SALARIO) values ('2','BENZEMA','1','DELANTERO CENTRO','9','20000');
Insert into HR.JUGADOR (JUGADOR_ID,NOMBRE,EQUIPO_ID,POSICION,NUMERO_CAMISETA,SALARIO) values ('3','BALE','1','LATERAL ','11','1000');
Insert into HR.JUGADOR (JUGADOR_ID,NOMBRE,EQUIPO_ID,POSICION,NUMERO_CAMISETA,SALARIO) values ('4','NEYMAR','1','DELANTERO','10','25000');
REM INSERTING into HR.SEGUIDOR_PELIGROSO
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C007069
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007069" ON "HR"."AFICION" ("AFICION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007073
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007073" ON "HR"."CANTICO" ("CANTICO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007035
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007035" ON "HR"."EQUIPO" ("EQUIPO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007032
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007032" ON "HR"."ESTADIO" ("ESTADIO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007039
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007039" ON "HR"."JUGADOR" ("JUGADOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007078
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007078" ON "HR"."SEGUIDOR_PELIGROSO" ("SEGUIDOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table AFICION
--------------------------------------------------------

  ALTER TABLE "HR"."AFICION" ADD PRIMARY KEY ("AFICION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."AFICION" MODIFY ("NOMBRE_DE_GUERRA" NOT NULL ENABLE);
  ALTER TABLE "HR"."AFICION" MODIFY ("AFICION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CANTICO
--------------------------------------------------------

  ALTER TABLE "HR"."CANTICO" ADD PRIMARY KEY ("CANTICO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."CANTICO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "HR"."CANTICO" MODIFY ("CANTICO_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIPO
--------------------------------------------------------

  ALTER TABLE "HR"."EQUIPO" ADD PRIMARY KEY ("EQUIPO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."EQUIPO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "HR"."EQUIPO" MODIFY ("EQUIPO_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESTADIO
--------------------------------------------------------

  ALTER TABLE "HR"."ESTADIO" ADD PRIMARY KEY ("ESTADIO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."ESTADIO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "HR"."ESTADIO" MODIFY ("ESTADIO_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table JUGADOR
--------------------------------------------------------

  ALTER TABLE "HR"."JUGADOR" ADD PRIMARY KEY ("JUGADOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."JUGADOR" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "HR"."JUGADOR" MODIFY ("JUGADOR_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SEGUIDOR_PELIGROSO
--------------------------------------------------------

  ALTER TABLE "HR"."SEGUIDOR_PELIGROSO" ADD PRIMARY KEY ("SEGUIDOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."SEGUIDOR_PELIGROSO" MODIFY ("DNI" NOT NULL ENABLE);
  ALTER TABLE "HR"."SEGUIDOR_PELIGROSO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "HR"."SEGUIDOR_PELIGROSO" MODIFY ("SEGUIDOR_ID" NOT NULL ENABLE);
